ALTER TABLE posts ADD COLUMN IF NOT EXISTS videos TEXT[] NOT NULL DEFAULT '{}';
ALTER TABLE posts ADD COLUMN IF NOT EXISTS audio_track JSONB DEFAULT NULL;

CREATE TABLE IF NOT EXISTS post_media (
  post_id UUID PRIMARY KEY REFERENCES posts(id) ON DELETE CASCADE,
  videos TEXT[] NOT NULL DEFAULT '{}',
  audio_track JSONB DEFAULT NULL,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
